
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root_password
  host: db
  port: 3306

development:
  <<: *default
  database: dev_db

test:
  <<: *default
  database: test_db

# production:
#   <<: *default
#   database: db/production
